# Generated by Django 5.0.6 on 2024-06-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Huevo',
            new_name='Producto',
        ),
    ]
