# Generated by Django 5.0.6 on 2024-06-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_web', '0002_rename_huevo_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='nombreProducto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precioProducto',
        ),
    ]
