# Generated by Django 5.0.3 on 2024-06-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_web', '0003_rename_nombre_producto_nombreproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipohuevo',
            field=models.CharField(max_length=50),
        ),
    ]
